def pwd(path) [File.dirname(__FILE__), path].join('/'); end

# Setup

src_dir = pwd('src/')
bin_dir = pwd('bin/')
all_classes = pwd('bin/*')
test_dir = pwd('test/')
junit = pwd('lib/junit-4.6.jar')
mockito = pwd('lib/mockito-all-1.7.jar')

javac_flags = "-Xlint:deprecation -Xlint:unchecked -d #{bin_dir} -sourcepath #{src_dir}"
javac_cmd = "javac #{javac_flags}"
classpath_flags = %Q[-cp "#{bin_dir}:#{junit}:#{mockito}"]

# Tasks

task :build do
  sh %{rm -fr #{all_classes}}
  sh %{find #{src_dir} -name *.java | xargs #{javac_cmd}}
end
task(:build_test => :build) { sh %{find #{test_dir} -name *.java | xargs #{javac_cmd} #{classpath_flags}} }
task(:test => :build_test) { sh %{java #{classpath_flags} gus.TestSuite} }

task :default => :test
